name: Docker CI

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 17

      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Push Docker image
        with:
          image: hectorbed/microservicio-saludo
          tags: ${{ github.sha }}
          registry: docker.io
          dockerfile: Dockerfile
          username: hectorbed
          password: ${{ secrets.CLAVE }}
