name: Docker CI

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: write      # Allows pushing code to the repository
      actions: read        # Allows reading workflow files
      issues: write        # Allows creating or updating issues
      pull-requests: write # Allows creating or updating pull requests

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 17

      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Push Docker image
        with:
          image: hectorbed/microservicio-saludo
          tags: ${{ github.sha }}
          registry: docker.io
          dockerfile: Dockerfile
          username: hectorbed
          password: ${{ secrets.CLAVE }}
      - name: Clone deployment repository
        env:
          EXTERNAL_REPO: 'https://github.com/hectorbed/proyecto-basico-k8s.git'
          BRANCH: 'main'
        run: |
          git clone --single-branch --branch ${{ env.BRANCH }} ${{ env.EXTERNAL_REPO }} proyecto-basico-k8s
          cd proyecto-basico-k8s
      - name: yq - portable yaml processor
        uses: mikefarah/yq@v4.44.3
      - name: Set new image tag
        env:
          IMAGE_NAME: hectorbed/microservicio-saludo
          NEW_TAG: ${{ env.GIT_SHA_SHORT }}
        run: |
          cd proyecto-basico-k8s
          yq eval ".spec.template.spec.containers[0].image = \"${{ env.IMAGE_NAME }}:${{ github.sha }}\"" -i componente_saludo_deployment.yaml
      - name: Commit changes in external repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd proyecto-basico-k8s
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Actualiza imagen a ${{ env.IMAGE_NAME }}:${{ github.sha }}"
          git remote set-url origin https://x-access-token:${{ env.GITHUB_TOKEN }}@github.com/hectorbed/proyecto-basico-k8s.git
          git push origin main